package main

import (
	"net/http"
	"testing"

	"github.com/dejavxtrem/snippetbox/internal/assert"
)

func TestPing(t *testing.T) {
	// Create a new instance of our application struct. For now, this just
	// contains a structured logger (which uses the slog.DiscardHandler handler
	// and will discard anything written to it with no action).
	// app := &application{
	// 	logger: slog.New(slog.DiscardHandler),
	// }
	app := newTestApplication(t)
	ts := newTestServer(t, app.routes())
	defer ts.Close()

	res := ts.get(t, "/ping")
	assert.Equal(t, res.status, http.StatusOK)
	assert.Equal(t, res.body, "OK")
	// We then use the httptest.NewTLSServer() function to create a new test
	// server, passing in the value returned by our app.routes() method as the
	// handler for the server. This starts up an HTTPS server which listens on a
	// randomly-chosen port of your local machine for the duration of the test.
	// Notice that we defer a call to ts.Close() so that the server is shut down
	// when the test finishes.
	// ts := httptest.NewTLSServer(app.routes())
	// defer ts.Close()

	// // Initialize a new httptest.ResponseRecorder.
	// // rr := httptest.NewRecorder()

	// // Initialize a new dummy http.Request.
	// // The network address that the test server is listening on is contained in
	// // the ts.URL field. We can use this to construct a new HTTP request for the
	// // GET /ping route.
	// req, err := http.NewRequest(http.MethodGet, ts.URL+"/ping", nil)
	// if err != nil {
	// 	t.Fatal(err)
	// }

	// // Use the ts.Client().Do() method to execute the request against the test
	// // server. This returns an http.Response struct containing the response.
	// res, err := ts.Client().Do(req)
	// if err != nil {
	// 	t.Fatal(err)
	// }
	// defer res.Body.Close()

	// // Call the ping handler function, passing in the
	// // httptest.ResponseRecorder and http.Request.
	// //ping(rr, req)

	// // Call the Result() method on the http.ResponseRecorder to get the
	// // http.Response generated by the ping handler.
	// // res := rr.Result()
	// // defer res.Body.Close()

	// // Check that the status code written by the ping handler was 200.
	// assert.Equal(t, res.StatusCode, http.StatusOK)

	// // And we can check that the response body written by the ping handler
	// // equals "OK".
	// body, err := io.ReadAll(res.Body)
	// if err != nil {
	// 	t.Fatal(err)
	// }
	// body = bytes.TrimSpace(body)
	// assert.Equal(t, string(body), "OK")
}
