package main

import (
	"net/http"
	"strings"
	"testing"

	"github.com/dejavxtrem/snippetbox/internal/assert"
)

func TestPing(t *testing.T) {
	// Create a new instance of our application struct. For now, this just
	// contains a structured logger (which uses the slog.DiscardHandler handler
	// and will discard anything written to it with no action).
	// app := &application{
	// 	logger: slog.New(slog.DiscardHandler),
	// }
	app := newTestApplication(t)
	ts := newTestServer(t, app.routes())
	defer ts.Close()

	res := ts.get(t, "/ping")
	assert.Equal(t, res.status, http.StatusOK)
	assert.Equal(t, res.body, "OK")
	// We then use the httptest.NewTLSServer() function to create a new test
	// server, passing in the value returned by our app.routes() method as the
	// handler for the server. This starts up an HTTPS server which listens on a
	// randomly-chosen port of your local machine for the duration of the test.
	// Notice that we defer a call to ts.Close() so that the server is shut down
	// when the test finishes.
	// ts := httptest.NewTLSServer(app.routes())
	// defer ts.Close()

	// // Initialize a new httptest.ResponseRecorder.
	// // rr := httptest.NewRecorder()

	// // Initialize a new dummy http.Request.
	// // The network address that the test server is listening on is contained in
	// // the ts.URL field. We can use this to construct a new HTTP request for the
	// // GET /ping route.
	// req, err := http.NewRequest(http.MethodGet, ts.URL+"/ping", nil)
	// if err != nil {
	// 	t.Fatal(err)
	// }

	// // Use the ts.Client().Do() method to execute the request against the test
	// // server. This returns an http.Response struct containing the response.
	// res, err := ts.Client().Do(req)
	// if err != nil {
	// 	t.Fatal(err)
	// }
	// defer res.Body.Close()

	// // Call the ping handler function, passing in the
	// // httptest.ResponseRecorder and http.Request.
	// //ping(rr, req)

	// // Call the Result() method on the http.ResponseRecorder to get the
	// // http.Response generated by the ping handler.
	// // res := rr.Result()
	// // defer res.Body.Close()

	// // Check that the status code written by the ping handler was 200.
	// assert.Equal(t, res.StatusCode, http.StatusOK)

	// // And we can check that the response body written by the ping handler
	// // equals "OK".
	// body, err := io.ReadAll(res.Body)
	// if err != nil {
	// 	t.Fatal(err)
	// }
	// body = bytes.TrimSpace(body)
	// assert.Equal(t, string(body), "OK")
}

func TestSnippetView(t *testing.T) {
	// Create a new instance of our application struct which uses the mocked
	// dependencies.
	app := newTestApplication(t)

	// Establish a new test server for running end-to-end tests.
	ts := newTestServer(t, app.routes())
	defer ts.Close()

	// Set up some table-driven tests to check the responses sent by our
	// application for different URLs.
	test := []struct {
		name       string
		urlPath    string
		wantStatus int
		wantBody   string
	}{
		{
			name:       "Valid ID",
			urlPath:    "/snippet/view/1",
			wantStatus: http.StatusOK,
			wantBody:   "An old silent pond...",
		},
		{
			name:       "Non-existent ID",
			urlPath:    "/snippet/view/2",
			wantStatus: http.StatusNotFound,
		},
		{
			name:       "Negative ID",
			urlPath:    "/snippet/view/-1",
			wantStatus: http.StatusNotFound,
		},
		{
			name:       "Decimal ID",
			urlPath:    "/snippet/view/1.23",
			wantStatus: http.StatusNotFound,
		},
		{
			name:       "String ID",
			urlPath:    "/snippet/view/foo",
			wantStatus: http.StatusNotFound,
		},
		{
			name:       "Empty ID",
			urlPath:    "/snippet/view/",
			wantStatus: http.StatusNotFound,
		},
	}

	for _, tt := range test {
		t.Run(tt.name, func(t *testing.T) {
			// Reset the test server client's cookie jar at the start of each
			// sub-test, so that any cookies set in previous tests are removed
			// and don't affect this test.
			ts.resetClientCookieJar(t)

			res := ts.get(t, tt.urlPath)
			//Use assert.Equal() to check the response status, and the
			// assert.True() function in conjunction with strings.Contains() to
			// make sure that the response body contains the expected content.
			assert.Equal(t, res.status, tt.wantStatus)
			assert.True(t, strings.Contains(res.body, tt.wantBody))
		})
	}

}
